### ISSUE TITLE
Riot has changed their webpage structure, therefore no recent RSS update

### ISSUE THREAD

**Issue by zzz6839** [Antosik/rito-news-feeds#5]
![image](https://github.com/Antosik/rito-news-feeds/assets/57741549/1430ee32-3ff4-477c-819a-66ea41bf0108)

**Comment by Antosik** [comment]
Hi @zzz6839,

Thank you for the report <3

I have just deployed a new version of the API and feeds. Could you please verify if everything is working correctly now? Additionally, all API and feeds are now accessible via the data.rito.news domain, so the full links will now look like https://data.rito.news/lol/zh-tw/news.json.
